### ISSUE TITLE
Resizing Support for Auto Layout

### ISSUE THREAD

**Issue by nschum** [shpakovski/MASPreferences#19]
When using Auto Layout, the autoresizing masks can't be set to indicate a fixed width or height.

https://github.com/jpvasquez/MASPreferences/commit/d1c9356332ef326ee9f507a91be4f7bb14b30572 apparently fixes this by adding an optional property to the protocol. Please consider adding something similar.

**Comment by shpakovski** [comment]
@nschum Not sure how this can be fixed. Do you still need this in `MASPreferences`? Thanks!
