### ISSUE TITLE
ToolBar Buttons not visible when used as Sheet in Yosemite

### ISSUE THREAD

**Issue by SDPrio** [shpakovski/MASPreferences#30]
Hi,

I am testing the latest version of MASPreferences in the current Yosemite Beta (GM candidate 1) and for some reason the ToolBar Buttons are not displayed when the preference window is displayed as Sheet.

You can simple reproduce the issue in the MASPreferences Demo:
- go to (IBAction)openPreferences:(id)sender in DemoAppDelegate
- Replace [self.preferencesWindowController showWindow:nil] with [self.window beginSheet:self.preferencesWindowController.window completionHandler:nil]

This will show the window as sheet but without the ToolBar Buttons. I am not sure if this a bug in Yosemite or in MASPreferences. Do you know this issue? Does anyone know how solve or bypass this problem?

Thanks!

**Comment by shpakovski** [comment]
@SDPrio Did you get any reply from the AppKit Team, by chance? Thanks!
