### ISSUE TITLE
Responder chain loop in OS X 10.10 (Yosemite)

### ISSUE THREAD

**Issue by MiMo42** [shpakovski/MASPreferences#37]
Patching the responder chain causes a responder chain loop here. Yosemite automatically adds view controllers to responder chain. Simply set NSResponderDebugResponderLoops=YES for debugging and the loop will be detected.
Here is what you get:
2015-03-19 14:13:14.752 Demo[1719:20436] NSResponderDebugResponderLoops=YES
2015-03-19 14:13:18.674 Demo[1719:20436] Responder chain loop detected! Calling [NSWindow setNextResponder:] self=<NSWindow: 0x6100001e6100>, aResponder=<GeneralPreferencesViewController: 0x6100000c44b0>
2015-03-19 14:13:18.674 Demo[1719:20436] You have a loop in the responder chain: this is a programming error
2015-03-19 14:13:18.676 Demo[1719:20436] (
	0   CoreFoundation                      0x00007fff9722050c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff911ff76e objc_exception_throw + 43
	2   AppKit                              0x00007fff941ab088 -[NSResponder setNextResponder:] + 368
	3   Demo                                0x0000000100003fc1 -[MASPreferencesWindowController patchResponderChain] + 193
	4   Demo                                0x0000000100005725 -[MASPreferencesWindowController setSelectedViewController:] + 5157
	5   Demo                                0x0000000100002d9d -[MASPreferencesWindowController windowDidLoad] + 413
	6   AppKit                              0x00007fff943416c7 -[NSWindowController _windowDidLoad] + 586
	7   AppKit                              0x00007fff943299f3 -[NSWindowController window] + 110
	8   AppKit                              0x00007fff9433ba42 -[NSWindowController showWindow:] + 36
	9   Demo                                0x0000000100001fa5 -[DemoAppDelegate openPreferences:] + 85
	10  libsystem_trace.dylib               0x00007fff90377cd7 _os_activity_initiate + 75
	11  AppKit                              0x00007fff943c9bd1 -[NSApplication sendAction:to:from:] + 452
	12  AppKit                              0x00007fff943df6e6 -[NSControl sendAction:to:] + 86
	13  AppKit                              0x00007fff943df602 __26-[NSCell _sendActionFrom:]_block_invoke + 131
	14  libsystem_trace.dylib               0x00007fff90377cd7 _os_activity_initiate + 75
	15  AppKit                              0x00007fff943df55f -[NSCell _sendActionFrom:] + 144
	16  libsystem_trace.dylib               0x00007fff90377cd7 _os_activity_initiate + 75
	17  AppKit                              0x00007fff943dda33 -[NSCell trackMouse:inRect:ofView:untilMouseUp:] + 2821
	18  AppKit                              0x00007fff944360df -[NSButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 770
	19  AppKit                              0x00007fff943dc0e6 -[NSControl mouseDown:] + 714
	20  AppKit                              0x00007fff94944b4c -[NSWindow _reallySendEvent:isDelayedEvent:] + 14125
	21  AppKit                              0x00007fff942d5b16 -[NSWindow sendEvent:] + 470
	22  AppKit                              0x00007fff942d20a2 -[NSApplication sendEvent:] + 2504
	23  AppKit                              0x00007fff941fbae8 -[NSApplication run] + 711
	24  AppKit                              0x00007fff94178284 NSApplicationMain + 1832
	25  Demo                                0x0000000100001cb2 main + 34
	26  Demo                                0x0000000100001c64 start + 52
)

**Comment by shpakovski** [comment]
Thanks for the heads up, any suggestion how to fix this? Sorry for the slow reply.

**Comment by sorbits** [comment]
I pushed a suggested fix to my fork, although I currently don’t have a 10.10 machine to test it on.

**Comment by shpakovski** [comment]
Looks good :) @MiMo42 Could you please verify the fix?

**Comment by MiMo42** [comment]
Thank you for the fix. It works for me.

**Comment by shpakovski** [comment]
Allan, I made you a collaborator. Please feel free to push the change. Thanks in advance :)
