### ISSUE TITLE
viewDidDisappear called twice

### ISSUE THREAD

**Issue by iwankerl** [shpakovski/MASPreferences#39]
This is the same problem that was seen with viewWillAppear in #32 

My app had some code that setup KVO in viewWillAppear and tore it down in viewWillDisapper.  The first time it was called, removing the KVO observers worked fine.  Then it was called a second time and my code wasn't handling this properly so it tried to remove the observers again which threw an exception.

**Comment by shpakovski** [comment]
Thanks a lot for the heads up! Care to create a Pull Request? 😉

**Comment by iwankerl** [comment]
I can but it may be a few days before I get to it.
