### ISSUE TITLE
MASPreferences compatibility carthage?

### ISSUE THREAD

**Issue by salexkidd** [shpakovski/MASPreferences#40]
Dear shpakovski

Now, I'm using MASPreferences & MASShortcut.
These are great projects!

MASShortcut has compatible in Carthage, But MASPreferences is not compatible.
Do you have plans for support carthage?

Thx!

**Comment by shpakovski** [comment]
Hello, please try the following port: https://github.com/mattprowse/MASPreferences Does it work for you? Sorry for the slow reply.

**Comment by salexkidd** [comment]
Thank you for your reply. I'll try your teaching repository!

**Comment by shpakovski** [comment]
@salexkidd Is this still a problem? Are you able to integrate `MASPreferences` via Carthage?
