### ISSUE TITLE
Getting error while setting up in Swift

### ISSUE THREAD

**Issue by bipinvaylu** [shpakovski/MASPreferences#43]
I am getting this error while inheriting MASPreferencesViewController. Can you please provide some more guideline about integrating in swift project. Not getting much from swift edge case description.

```
import MASPreferences
public class PrefsController: MASPreferencesViewController {
    
}
```
Getting errors: 
```
Type 'PrefsController' does not conform to protocol 'MASPreferencesViewController'
Type 'PrefsController' does not conform to protocol 'NSObjectProtocol'
```

And do i need to import anything in app-Bridging-Header.h file?

**Comment by ianyh** [comment]
`MASPreferencesViewController` is a protocol, not a class. The code should be:
```swift
public class PrefsController: NSViewController, MASPreferencesViewController {

}
```

**Comment by shpakovski** [comment]
Thank @ianyh!

**Comment by ianyh** [comment]
You are quite welcome!

**Comment by bipinvaylu** [comment]
Thanks :)
