### ISSUE TITLE
NSAppearanceNameVibrantDark support?

### ISSUE THREAD

**Issue by alfio86** [shpakovski/MASPreferences#52]
A bool or something like and choose between NSAppearanceNameVibrantDark and NSAppearanceNameAqua?

**Comment by Ben10do** [comment]
It might be nice as a convenience option, but if you subclass `MASPreferencesWindowController`, it's not tricky to do something like:

```swift
override func windowDidLoad() {
    super.windowDidLoad()
    window?.appearance = NSAppearance(named: NSAppearanceNameVibrantDark)
}
```

**Comment by shpakovski** [comment]
👏
