### ISSUE TITLE
Customising tabs

### ISSUE THREAD

**Issue by benjam1n** [shpakovski/MASPreferences#53]
Hi, Vadim and others!

Is there an ideas way to change font size, icon size, active tab background and similar (what seem to be) basic properties? I explored all the component code but I can't figure it out. 

![screen shot 2017-05-18 at 15 43 11](https://cloud.githubusercontent.com/assets/103969/26205057/eaccc37a-3be0-11e7-9bf9-b2c659ce039f.png)

It's probably trivial since there isn't anything on the web about but the thing is I've never opened Xcode until 10 days ago and I'm actually a designer - so please don't tell me to *subclass* something... :D

Thanks!

**Comment by shpakovski** [comment]
Hi Benjamin!

Unfortunately, it’s very hard to customize `NSToolbar` in Cocoa. It’s probably easier to develop your own component 🤷‍♂️

Sorry for the slow reply.
