### ISSUE TITLE
Podspec & Version Bump

### ISSUE THREAD

**Issue by Coder-256** [shpakovski/MASPreferences#55]
Could you please run `pod trunk push MASPreferences.podspec`? You should run that after each version bump so that the new version can be automatically downloaded by users when they run `pod update`.

Speaking of which, could you please consider doing a version bump too? I am trying to use the 10.13 SDK for my app, which is incompatible with the latest release (1.2, or as far as Cocoapods is concerned, 1.1.4).

**Comment by shpakovski** [comment]
Done, could you please verify! Sorry for the slow reply.

**Comment by Coder-256** [comment]
That worked, thank you!
