### ISSUE TITLE
Does not conform to MASPreferencesViewController

### ISSUE THREAD

**Issue by klische** [shpakovski/MASPreferences#56]
The snippet in the readme does not work

##Swift Edge case When using Swift you need to override the identifier from MASPreferencesViewController the following to be compatible with the mutable identifier String? in NSViewController

override var identifier: String? { get {return "general"} set { super.identifier = newValue} }

Platform: Xcode 8.3.3, macOS 10.12 SDK & target

**Comment by klische** [comment]
The MASPreferences framework was built with Carthage. Could this be the issue? I just tried adding a TestViewController.swift into the MASPreferencesDemo project, and it works perfectly fine with the above snippet. In fact, it doesn't even require that the identifier is overriden.

**Comment by dabbott** [comment]
This happens to me too, after upgrading from 1.1.4 to 1.2.1.

It seems like Swift can't figure out what to do with the `NSUserInterfaceItemIdentifier` type from this commit https://github.com/shpakovski/MASPreferences/commit/7b656d2d6b9161baeed4aadcc61d62c11c6839a1#diff-67d386f0a394ad12ea639324958fe1d0R10. Xcode toggles between two states: it first offers to "fix" protocol compliance by adding a `var identifier: NSUserInterfaceItemIdentifier`. If I do that, it then offers to "fix" protocol compliance by converting `identifier` to a `String?`. Which puts it back in the initial state.

I don't have much experience with Obj-C, so I'm not sure what the solution is. I'm going to stick with 1.1.4 for now.

**Comment by klische** [comment]
I ended up taking the MASPreferences.framework generated by CocoaPods and it does not complain about the InterfaceItemIdentifier. I'm not sure why the framework output by CocoaPods would work but Carthage or compiling it in Xcode does not.

**Comment by shpakovski** [comment]
🙇

**Comment by sorbits** [comment]
Can someone try again with `HEAD`?

We have renamed the `identifier` property to `viewIdentifier` so that it no longer clashes with the user interface validation protocol.
