### ISSUE TITLE
Cannot add an initialiser with no arguments in subclasses of MASPreferencesWindowController

### ISSUE THREAD

**Issue by Ben10do** [shpakovski/MASPreferences#57]
As a convenience, I currently subclass `MASPreferencesWindowController` (from Swift, if it makes any difference), and initialise it with the various view controllers that I'd like to use in my preferences window. In MASPreferences 1.1.4, it would look something like this:
```swift
init() {
    super.init(viewControllers: [FirstPreferencesViewController(),
                                 SecondPreferencesViewController()],
               title: NSLocalizedString("Preferences", comment: "Preferences Title"))
}
```

However, since updating to MASPreferences 1.2.1, I've noticed that I can't use an initialiser without any arguments, as I'm told that I `cannot override 'init()' which has been marked unavailable: Please use initWithViewControllers:title:`. As a result, I'm having to declare my initialiser as `init(_: ())`, the closest I can get to no arguments.

It seems like this line in `MASPreferencesWindowController.h:72` is the cause:
```objective-c
- (instancetype)init __attribute((unavailable("Please use initWithViewControllers:title:")));
```

While I appreciate that it's a good way of preventing usage of `NSObject`'s default `- init` initialiser (accidental or otherwise), it's annoying that it also blocks subclasses from creating their own.

As I don't think is a particularly exotic use case, would it be possible to resolve this?

**Comment by shpakovski** [comment]
Hello Ben, thanks a lot for the feedback! I’d not like to encourage this kind of API usage. Could you please consider the following alternative?

```swift
class CustomPreferencesWindowController : NSWindowController {
    class func newController() {
        return init(
            viewControllers: [FirstPreferencesViewController(), SecondPreferencesViewController()],
            title: NSLocalizedString("Preferences", comment: "Preferences Title"))
    }
}
```

**Comment by Ben10do** [comment]
Hi Vadim, that could also work. Out of curiosity, is there any particular reason why you'd prefer not to encourage the usage above? Personally, I think that using these kinds of factory methods is something I'd be more likely to do in Objective-C than I would in Swift.

**Comment by shpakovski** [comment]
> Out of curiosity, is there any particular reason why you'd prefer not to encourage the usage above?

I believe in that famous “composition over inheritance” principle 🙈
