### ISSUE TITLE
Incorrect zoom button handling results in view positioning error

### ISSUE THREAD

**Issue by thecrypticace** [shpakovski/MASPreferences#6]
If one goes through a series of steps the view in the fixed-size preference pane is laid partially on top of the toolbar.

Steps:
1. Click "Preferences" button
2. Click "Advanced" tab
3. Click Zoom (green) button
4. Click "General" tab
5. Click Zoom (green) button
6. See the doom of everlasting NSView chaos (also known as the bug)

Link to screen recoding reproducing the above steps: http://cl.ly/FtxX
Link to picture showing aforementioned bug: http://cl.ly/FuZn

**Comment by shpakovski** [comment]
@thecrypticace I could not solve this last. Is this still relevant? Please let me know if it is still critical. Sorry for so late follow-up 😊

**Comment by thecrypticace** [comment]
Wow, I'd forgotten about this. I doubt its still relevant. Thanks for following up.
